name: Deploy Docs
on:
  push:
    branches:
      - main # 只有在推送到 main 分支时触发

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install dependencies
        run: |
          pip install mkdocs-material

      # 如果你不想移动文件，可以在这里用命令准备 docs 目录
      - name: Prepare docs folder
        run: |
          mkdir -p docs
          cp README.md docs/index.md
          cp API.md docs/API.md
          cp API.en.md docs/API.en.md

      - name: Build and Deploy
        run: mkdocs gh-deploy --force